I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script
    scene rain:
  File "game/script.rpy", line 11, in script
    scene rain:
Exception: Scene may not run while in init phase.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/ysrchf/Documents/Renpy/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/Users/ysrchf/Documents/Renpy/renpy-8.0.3-sdk/renpy/main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 11, in script
    scene rain:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 11, in script
    scene rain:
  File "/Users/ysrchf/Documents/Renpy/renpy-8.0.3-sdk/renpy/ast.py", line 1539, in execute
    renpy.config.scene(self.layer)
  File "/Users/ysrchf/Documents/Renpy/renpy-8.0.3-sdk/renpy/exports.py", line 769, in scene
    raise Exception("Scene may not run while in init phase.")
Exception: Scene may not run while in init phase.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Quel est notre premier souvenir 1.0
Wed Mar 29 01:08:19 2023
